# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ACR'
  imageRepository: 'modernapi'
  containerRegistry: 'holdevtestacriqp.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/apiapp.Dockerfile'
  tag: '$(Build.BuildNumber)'
  imageName: $(Build.DefinitionName):$(Build.BuildNumber)
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: Build and push the modernapi container and copy sql files
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push the api image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: | 
          $(tag)
          latest
    - task: CopyFiles@2
      displayName: Copy the sql deployment files
      inputs:
        SourceFolder: 'ModernApiApp.Database/deploy'
        Contents: '*.sql'
        TargetFolder: '$(build.artifactstagingdirectory)'
        flattenFolders: true
    - task: PublishBuildArtifacts@1
      displayName: Publish the sql deployment scripts to the artifacts drop
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'